form:
  name: 'Test form'
  steps:
    step1:
      template: foo
      rules:
        name:
          'Mike': :step3
      questions:
        - name: :name
          title: Your full name
          widget: :input
        - name: :postcode
          title: Your postcode
          widget: :input
    step2:
      template: bar
      next_step: :step4
      questions:
        - name: :email
          title: Email
          widget: :email
        - name: :phone_number
          title: Phone Number
          widget: :tel
    step3:
      template: :baz
    step4:
      template: :bar
      
      
